import { defineConfig } from "vitepress";

// The site is published to https://www.lpalbou.info/AgoraWUI/ by
// .github/workflows/docs.yml. `docs/reference/` is generated by TypeDoc
// (`npm run docs:api`) and is not committed.
export default defineConfig({
  title: "Agora WUI",
  description: "Framework-agnostic React Teams interface for an Agora Hub.",
  base: "/AgoraWUI/",
  lang: "en-US",
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: [/^https?:\/\/(127\.0\.0\.1|localhost)/, /^\.\.\//],
  head: [["meta", { name: "color-scheme", content: "dark light" }]],
  srcExclude: ["plan/**", "spec/**", "README.md"],
  themeConfig: {
    nav: [
      { text: "Guide", link: "/getting-started" },
      { text: "API", link: "/api" },
      { text: "Reference", link: "/reference/" },
      { text: "Changelog", link: "/changelog" },
    ],
    sidebar: [
      {
        text: "Guide",
        items: [
          { text: "Overview", link: "/" },
          { text: "Getting started", link: "/getting-started" },
          { text: "Architecture", link: "/architecture" },
          { text: "FAQ", link: "/faq" },
          { text: "Troubleshooting", link: "/troubleshooting" },
        ],
      },
      {
        text: "API",
        items: [
          { text: "Public API", link: "/api" },
          { text: "Generated reference", link: "/reference/" },
        ],
      },
      {
        text: "Project",
        items: [
          { text: "Changelog", link: "/changelog" },
          { text: "Contributing", link: "/contributing" },
          { text: "Security", link: "/security" },
        ],
      },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/lpalbou/AgoraWUI" }],
    search: { provider: "local" },
    editLink: {
      pattern: "https://github.com/lpalbou/AgoraWUI/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    footer: {
      message: "Released under the MIT License.",
      copyright: "Copyright © Laurent-Philippe Albou",
    },
  },
});
